name: Tag Bump

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'
    secrets:
      devpi_username: 
        required: true
      devpi_password: 
        required: true

jobs:
  publish: 
    runs-on: ${{ inputs.runner_label }}
    env: 
      UV_PYTHON_INSTALL_DIR: C:\ProgramData\AIBS_MPE\uv_python
      UV_TOOL_DIR: C:\ProgramData\AIBS_MPE\uv_python
    steps:
      - name: Install UV 
        uses: astral-sh/setup-uv@v5
      - name: Build Project
        run: uv build
      - name: Publish Project to eng-tools devpi
        # TODO: implement and use devpi-token
        run: uv publish --publish-url http://eng-tools:3141/aibs/packages --username ${{ secrets.devpi_username}} --password ${{ secrets.devpi_password }}
