name: Python Tests

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'

jobs: 
  run-tests: 
    runs-on: ${{ inputs.runner_label }}
    env: 
      UV_PYTHON_INSTALL_DIR: C:\ProgramData\AIBS_MPE\uv_python
      UV_TOOL_DIR: C:\ProgramData\AIBS_MPE\uv_python
    strategy: 
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV - set python version to ${{ matrix.python-version }} 
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Unit test with PyTest  
      run: uv run pytest tests/