name: Python Type Check

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'

jobs: 
  type_check: 
    runs-on: ${{ inputs.runner_label }}
    strategy: 
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV - set python version to ${{ matrix.python-version }} 
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Type check with mypy 
      run: |
        uv run mypy src/mypackage --strict